version: '3'

services:
  grwag.handicap:
    image: grwag/handicap:${TAG}
    container_name: 'handicap'
    restart: on-failure
    networks:
      - proxy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OAUTH_ISSUER=${OAUTH_ISSUER}
      - OAUTH_SCOPE=${OAUTH_SCOPE}
      - OAUTH_REPONSE_TYPE=${OAUTH_REPONSE_TYPE}
      - OAUTH_REDIRECT_URI=${OAUTH_REDIRECT_URI}
      - OAUTH_POST_LOGOUT_REDIRECT_URI=${OAUTH_POST_LOGOUT_REDIRECT_URI}
      - LETSENCRYPT_HOST=pbc.greshawag.com
      - LETSENCRYPT_EMAIL=cert@greshawag.com
      - VIRTUAL_HOST=pbc.greshawag.com
      - VIRTUAL_PORT=80

networks:
  proxy:
    external:
      name: nginxproxy_nginx-proxy