version: '3'

services:
  mariadb:
    container_name: 'mariadb'
    image: mariadb
    restart: always
    volumes:
      - /data/mariadb:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=C78VRMJQucRN6XgbksxLmmaz
      - MYSQL_PASSWORD=Kk4Pm0oBEV8PMOTUwMcRN6wS
      - MYSQL_DATABASE=handicap
      - MYSQL_USER=handicap_user
  bzo.handicap:
    image: bzo/handicap
    container_name: 'handicap'
    restart: on-failure
    networks:
      - proxy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_PASSWORD=C78VRMJQucRN6XgbksxLmmaz
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=handicap
